### ISSUE TITLE
有没有随机壁纸的想法？

### ISSUE THREAD

**Issue by LspColor** [MicroCBer/BetterNCM-Installer#12]
壁纸全放一个路径，每次启动换一个，也可以整个自适应模糊或者自定义模糊?

**Comment by MicroCBer** [comment]
把v2做完先）

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/186117758-f7922a86-1ffd-434c-80a2-7da6b7f98fe6.png)
已完成
