### ISSUE TITLE
主题和背景应用之后，打开歌词界面一半背景很亮一半很暗

### ISSUE THREAD

**Issue by UlbertLEE** [MicroCBer/BetterNCM-Installer#14]
![XVX66`V%SJWYJ12L3EYE9UC](https://user-images.githubusercontent.com/111230517/184536757-1859f6c1-2533-48b4-9db4-1577fa5145aa.png)
如图

**Comment by Yamds** [comment]
>你试试在css里加上这个?
 .bg.j-flag {
  display: none;
}

**Comment by MicroCBer** [comment]
@沫烬染
