### ISSUE TITLE
用motheme主题后，每次换完歌曲，左下角的专辑图片就会红几秒

### ISSUE THREAD

**Issue by mayjack0312** [MicroCBer/BetterNCM-Installer#15]
用motheme主题后，每次换完歌曲，左下角的专辑图片就会红几秒
![image](https://user-images.githubusercontent.com/102800660/184583870-f7332f09-c5d4-4609-8e1e-6d6f8043a6f1.png)

**Comment by VitiaOfficial** [comment]
我猜下个版本就没这问题了

**Comment by mayjack0312** [comment]
> 我猜下个版本就没这问题了

好滴，大佬辛苦啦 (๑′ᴗ‵๑)Ｉ Lᵒᵛᵉᵧₒᵤ❤

**Comment by VitiaOfficial** [comment]
我不是作者...我只是猜测

**Comment by MicroCBer** [comment]
这个我已经在我的主题里面修复了，不过这个主题不是我写的，得问这个作者了

**Comment by mayjack0312** [comment]
> 我不是作者...我只是猜测

(*^▽^*)好的

**Comment by mayjack0312** [comment]
> 这个我已经在我的主题里面修复了，不过这个主题不是我写的，得问这个作者了

欧克克
