### ISSUE TITLE
安装器无法安装

### ISSUE THREAD

**Issue by WinTerminal** [MicroCBer/BetterNCM-Installer#2]
环境：Win10 21H2
就在这个界面卡死，无法安装，重试、WD 添加信任无效
![image](https://user-images.githubusercontent.com/104144911/164459231-a5498784-4299-4f08-8970-9680d8041d94.png)

**Comment by WinTerminal** [comment]
是不是因为安装目录有中文？

**Comment by MicroCBer** [comment]
可以参考 #1 这个issue

访问了github 所以对网络环境有要求

预计下个版本增设gitee / fastgit的镜像

**Comment by Emperor-Xpress** [comment]
额我就不另开issue了
我的installer无法运行 甚至无法打开🤦‍♂️右击管理员运行也不行
