### ISSUE TITLE
安装后网易云无法打开

### ISSUE THREAD

**Issue by ArisCM** [MicroCBer/BetterNCM-Installer#20]
0.1.2版本安装完成后弹窗提示网易云崩溃后无法打开网易云，安装完成后也没有提示安装自签证书，卸载后恢复正常
0.1.1版本安装完成后提示此软件无法在你的系统上运行，安装器在安装完成后就打不开了，得用0.1.2版本卸载才能恢复正常

网易云及系统版本如下

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎5/‎19
操作系统版本	22621.575
体验	Windows Feature Experience Pack 1000.22634.1000.0

![QQ截图20220819192811](https://user-images.githubusercontent.com/85684519/185609700-bd518d75-8ada-4028-a698-56473baef7ef.png)

![QQ截图20220819192914](https://user-images.githubusercontent.com/85684519/185609706-4bb4f0fb-dfb8-41d5-984a-25291dca8e68.png)

**Comment by ArisCM** [comment]
系统防火墙已关闭，路由器带国际访问，火绒已添加白名单，尝试过管理员运行和兼容性运行均无效

**Comment by MicroCBer** [comment]
网易云版本必须>=2.10.2，目前仅适配更新了Chrome91的网易云
