### ISSUE TITLE
关于新版本的一些建议

### ISSUE THREAD

**Issue by Kirs-Mio** [MicroCBer/BetterNCM-Installer#21]
![image](https://user-images.githubusercontent.com/104182535/185727144-31e73618-3ac8-47ab-8c50-935f26b74b0f.png)
  这里可以多加几项吗？之前不是可以设置是否显示轮播图，还有收藏云盘等等。另外我很喜欢这个主题，但播放页，那个黑胶是网易云音乐的特色，能不能也弄一个这样的开关，我现在似乎改那个配置文件弄回来了。还有界面字体颜色可以弄个自定义颜色嘛。

**Comment by MicroCBer** [comment]
[x] 开关黑胶
[ ] 收藏云盘，轮播图隐藏 

自定义颜色不打算做 很麻烦
