### ISSUE TITLE
似乎无法为安装在其他盘符的网易云音乐安装此插件

### ISSUE THREAD

**Issue by KeeLee2005** [MicroCBer/BetterNCM-Installer#22]
网易云安装在D盘，Installer也显示安装在D盘，但是点击安装时闪过一个窗口，无法正常安装。再次安装网易云音乐至默认位置后才能正常安装此插件。

**Comment by MicroCBer** [comment]
无法正常安装是什么现象

**Comment by wlingzhenyu** [comment]
我也遇到了这个问题，在D盘目录打开网易云发现并没有成功，还是原版界面，关于网易云那些设置我都看了，但F12还能打开DEV tools

**Comment by wlingzhenyu** [comment]
我也遇到了这个问题，在D盘目录打开网易云发现并没有成功，还是原版界面，那些设置里的选项我都看了一遍，但F12还能打开DEV tools
只有按默认位置才能成功使用

**Comment by MicroCBer** [comment]
> 我也遇到了这个问题，在D盘目录打开网易云发现并没有成功，还是原版界面，那些设置里的选项我都看了一遍，但F12还能打开DEV tools 只有按默认位置才能成功使用

看下devtools里面有没有报错

**Comment by wlingzhenyu** [comment]
呃，没事了，我又尝试把网易云音乐装到D盘他就成功了
