### ISSUE TITLE
底部界面消失

### ISSUE THREAD

**Issue by VitiaOfficial** [MicroCBer/BetterNCM-Installer#24]
![CI 2SZT`LY90@QL`D2J3ASH](https://user-images.githubusercontent.com/110652274/186311648-a6288ca3-6d4f-4bac-b6fa-8c6b22faeb2a.png)
见图左下角
概率消失 原因不明
重启可以恢复
目前只遇见过一次

**Comment by MicroCBer** [comment]
无法复现，暂时不修
