### ISSUE TITLE
功能建议：自动切换自定义白天/夜晚主题

### ISSUE THREAD

**Issue by KiritoKing** [MicroCBer/BetterNCM-Installer#25]
如题所示，或者说开放第三方插件开发？
不是很懂这个插件是怎么搞的，和油猴类似？

**Comment by MicroCBer** [comment]
其实一直是开放的，还没来得及写文档

随便找个插件右键解压就能看到源码了

**Comment by MicroCBer** [comment]
自动切换自定义白天/夜晚主题是指根据背景图吗

**Comment by KiritoKing** [comment]
> 其实一直是开放的，还没来得及写文档
> 
> 随便找个插件右键解压就能看到源码了

好的 谢谢

**Comment by KiritoKing** [comment]
> 自动切换自定义白天/夜晚主题是指根据背景图吗

大概是这个意思 我的想法是读取系统暗色亮色主题更换 就是不知道有没有对应api

**Comment by MicroCBer** [comment]
问题是切换出来的可能和背景不搭（

如果你想做可以研究一下，在 https://gitee.com/microblock/better-ncm-v2-data 发pr就可以发布你自己的插件
