### ISSUE TITLE
最新版本1.2.0一直显示获取最新版本

### ISSUE THREAD

**Issue by KiWinger** [MicroCBer/BetterNCM-Installer#26]
![Snipaste_2022-08-24_19-45-39](https://user-images.githubusercontent.com/49084827/186410503-06a4c8d3-92dd-4f90-86ae-48d5f300ce0f.png)

如图，已搭梯与未搭梯均无效

**Comment by MicroCBer** [comment]
hyper可能不会走你梯子，可以手动安装一下
