### ISSUE TITLE
[功能要求] 安装器提供更新选项

### ISSUE THREAD

**Issue by IASUI** [MicroCBer/BetterNCM-Installer#32]
![Snipaste_2022-10-02_23-16-31](https://user-images.githubusercontent.com/66980246/193462186-21822453-a100-474b-905e-159ef428ad32.png)
如图，只有卸载后才能安装新版本，卸载后插件的数据没了。重新装下插件和改设置还行，但是背景增强插件的壁纸就得重新一个一个选择导入了，这就有点麻烦了。

**Comment by MicroCBer** [comment]
BetterNCM现在支持自更新
![KBT1G~VM_)VK7F _AF OSML](https://user-images.githubusercontent.com/66859419/193462659-700502cd-9a12-4c6b-a6f6-24ad5b4fe906.png)
