### ISSUE TITLE
网易云音乐无法正常迁移下载目录

### ISSUE THREAD

**Issue by vic233333** [MicroCBer/BetterNCM-Installer#38]
如题，当使用本插件时，即使未安装任何插件市场中的插件，依旧会导致网易云音乐无法迁移下载目录。如果尝试迁移，选择目录并点击重启应用后网易云音乐会自动关闭，但是不会自动开始迁移和自动启动网易云音乐，手动打开网易云音乐也会发现下载目录没有被迁移到指定位置。

**Comment by Maho9x** [comment]
有相同的问题

**Comment by MicroCBer** [comment]
请在对应repo下发issue 而不是Installer……

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
