### ISSUE TITLE
安装器自动闪退

### ISSUE THREAD

**Issue by gongfuture** [MicroCBer/BetterNCM-Installer#4]
安装器管理员打开，三秒后自动闪退

**Comment by MicroCBer** [comment]
确定能连上github吗

**Comment by gongfuture** [comment]
可以连上GitHub，并且两个版本都试了，都是这样

**Comment by gongfuture** [comment]
刚刚试了一下，又都可以用了

**Comment by gongfuture** [comment]
没能搞懂昨晚上为啥不能用。昨天还关了各种后台，关了Windows defence

**Comment by gongfuture** [comment]
镜像版本的日志好像找到了
[-](https://github.com/MicroCBer/BetterNCM-Installer/issues/4#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/MicroCBer/BetterNCM-Installer/issues/4#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-08-03T15:09:56.7851715Z" /> 
  <EventRecordID>73760</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>xxxxx</Computer> 
  <Security /> 
  </System>
[-](https://github.com/MicroCBer/BetterNCM-Installer/issues/4#) <EventData>
  <Data>betterncm_installer_cn_mirror.exe</Data> 
  <Data>0.1.1.0</Data> 
  <Data>62a47291</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.1865</Data> 
  <Data>dd841229</Data> 
  <Data>80000003</Data> 
  <Data>00000000000cda22</Data> 
  <Data>4900</Data> 
  <Data>01d8a74b1666a17f</Data> 
  <Data>d:\Users\xxxxx\Downloads\betterncm_installer_cn_mirror.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>52fed6cc-c56d-4dd3-b456-f5c82852127f</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

[CrashDumps.zip](https://github.com/MicroCBer/BetterNCM-Installer/files/9256105/CrashDumps.zip)

**Comment by gongfuture** [comment]
![image](https://user-images.githubusercontent.com/60888755/182747914-92d836cb-351c-4a76-8384-83c88cb77a33.png)

现在闪退又开始了

**Comment by gongfuture** [comment]
*** WARNING: Unable to verify checksum for betterncm_installer_cn_mirror.exe

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1406

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 31266

    Key  : Analysis.Init.CPU.mSec
    Value: 343

    Key  : Analysis.Init.Elapsed.mSec
    Value: 23678

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 108

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 1415

    Key  : Timeline.Process.Start.DeltaSec
    Value: 2

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1

    Key  : WER.Process.Version
    Value: 0.1.1.0


FILE_IN_CAB:  betterncm_installer_cn_mirror.exe.8040.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=0000000000000000 rbx=0000000000000450 rcx=f574b45706d90000
rdx=0000000000000000 rsi=00000000000002ff rdi=0000000000000000
rip=00007ffe7551da22 rsp=0000006d1f3eeea8 rbp=0000006d1f3ef840
 r8=0000006d1f3eed08  r9=0000006d1f3eed30 r10=0000000000000000
r11=0000000000000246 r12=00007ffe6694ab10 r13=0000000000000000
r14=0000000000000000 r15=00000186b23909c8
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
KERNELBASE!wil::details::DebugBreak+0x2:
00007ffe`7551da22 cc              int     3
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffe7551da22 (KERNELBASE!wil::details::DebugBreak+0x0000000000000002)
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 1
   Parameter[0]: 0000000000000000

PROCESS_NAME:  betterncm_installer_cn_mirror.exe

ERROR_CODE: (NTSTATUS) 0x80000003 - {    }

EXCEPTION_CODE_STR:  80000003

EXCEPTION_PARAMETER1:  0000000000000000

STACK_TEXT:  
0000006d`1f3eeea8 00007ffe`668ffa70     : 0000006d`1f3eeff0 0000006d`1f3ef4f0 00007ffe`6695fe50 00007ffe`6695fe90 : KERNELBASE!wil::details::DebugBreak+0x2
0000006d`1f3eeeb0 00007ffe`668ff0f7     : 00000186`00000450 00000000`00000000 0000006d`1f3ef118 0000006d`1f3ef140 : D2D1Debug3!DebugLayer::OutputGlobalErrorMessage+0x10c
0000006d`1f3ef810 00007ffe`668f5e98     : 00007ffe`72592e20 00000186`b2390e58 00000000`00000001 00007ffe`6d2d134e : D2D1Debug3!DebugLayer::GlobalCleanup+0x1cf
0000006d`1f3ef870 00007ffe`6694ac4f     : 00000000`00000001 0000006d`1f3efc80 0000006d`1f3efc80 00000000`00000000 : D2D1Debug3!DllMain+0x248
0000006d`1f3ef8d0 00007ffe`77889a1d     : 00007ffe`668f0000 00000000`00000000 00000000`00000001 00000000`7ffe0385 : D2D1Debug3!__DllMainCRTStartup+0xfb
0000006d`1f3efa40 00007ffe`778cdb91     : 00000186`b096ad50 00007ffe`668f0000 00000000`00000000 00000186`b096ad70 : ntdll!LdrpCallInitRoutine+0x61
0000006d`1f3efab0 00007ffe`778cda2d     : 00000000`00000065 00000000`00000000 00000186`b0972f20 00000000`00000000 : ntdll!LdrShutdownProcess+0x141
0000006d`1f3efbb0 00007ffe`7778e0ab     : 00000000`00000065 00000000`00000000 00007ffe`757dd3a0 0000006d`1f3efc80 : ntdll!RtlExitUserProcess+0xad
0000006d`1f3efbe0 00007ffe`757405bc     : 00000000`00000065 00000000`00000000 0000006d`1f3efc68 00007ffe`75810e40 : kernel32!ExitProcessImplementation+0xb
0000006d`1f3efc10 00007ffe`7574045f     : 00000000`00000065 00000000`00000000 00000186`b0972f20 0000006d`1f3efc60 : ucrtbase!exit_or_terminate_process+0x44
0000006d`1f3efc40 00007ff7`eaf4f5d3     : 00000000`00000065 00000000`00000000 00000000`00000000 00000000`00000001 : ucrtbase!common_exit+0x6f
0000006d`1f3efc90 00007ffe`77787034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : betterncm_installer_cn_mirror+0x2df5d3
0000006d`1f3efcd0 00007ffe`778c2651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
0000006d`1f3efd00 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  d2d1debug3!DebugLayer::OutputGlobalErrorMessage+10c

MODULE_NAME: D2D1Debug3

IMAGE_NAME:  D2D1Debug3.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_D2D1Debug3.dll!DebugLayer::OutputGlobalErrorMessage

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  10.0.19041.1

FAILURE_ID_HASH:  {4c77aeac-e050-04b4-b27e-9dfa0378b6fa}

Followup:     MachineOwner
---------

**Comment by MicroCBer** [comment]
整不明白）
既然能用了就行
