### ISSUE TITLE
安装1.0.0版本后网易云无法启动

### ISSUE THREAD

**Issue by zzzhxxx** [MicroCBer/BetterNCM-Installer#40]
如题，卸载重装网易云后仍然无法启动

**Comment by wuhang2003** [comment]
同情况+1
不管是测试通道还是目前的发布通道都会导致运行崩溃，如图
![image](https://user-images.githubusercontent.com/108316419/210565813-c90cf7e0-2995-498f-87e2-5eed90a6a254.png)
事件查看器提供的信息：
![image](https://user-images.githubusercontent.com/108316419/210566049-d36601d2-4fed-4b05-bf05-248a8b960116.png)

**Comment by MicroCBer** [comment]
如果以前安装过betterncm 可能需要删除原来的betterncm文件夹（即点击open folder出现的文件夹）

**Comment by wuhang2003** [comment]
> 如果以前安装过betterncm 可能需要删除原来的betterncm文件夹（即点击open folder出现的文件夹）

此方法测试后已可正常使用
是 1.0 改动太大了和老版本不兼容么？

**Comment by MicroCBer** [comment]
> > 如果以前安装过betterncm 可能需要删除原来的betterncm文件夹（即点击open folder出现的文件夹）
> 
> 此方法测试后已可正常使用 是 1.0 改动太大了和老版本不兼容么？

目前还不清楚..后面看看
