### ISSUE TITLE
1.0.2测试版安装出现问题

### ISSUE THREAD

**Issue by Reo-cosn** [MicroCBer/BetterNCM-Installer#42]
![图片1](https://user-images.githubusercontent.com/83768745/215952456-b1de5508-c942-45cb-9168-1509e4fbe0ac.png)
![image](https://user-images.githubusercontent.com/83768745/215952591-6159477e-eac9-437e-9abc-a1ec72b202b1.png)
## 系统信息
版本	Windows 11 专业版 Insider Preview
版本	22H2
安装日期	‎2023.‎01.‎27
操作系统版本	25284.1000
序列号	PF2CEPYF
体验	Windows Feature Experience Pack 1000.25284.1000.0

**Comment by MicroCBer** [comment]
测试通道现在是走 ghproxy 的，不是很稳定，装不上就是网络问题，没有办法

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Reo-cosn** [comment]
彳亍
