### ISSUE TITLE
安装插件之后网易云就打不开了

### ISSUE THREAD

**Issue by AliceIClodia** [MicroCBer/BetterNCM-Installer#43]

**Comment by AliceIClodia** [comment]
![VK3Q4PI3ANWJNFQKC%)`P@6](https://user-images.githubusercontent.com/120046369/216753249-1cca6c0a-1fe9-489a-a422-963a73f952d2.png)

**Comment by feng-or** [comment]
现在1.2.0有问题会有报错提示，如果没有就大概率是dll文件缺库没法运行，可以打个微软常用运行库试试

**Comment by MicroCBer** [comment]
请使用最新版 Installer...
