### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by HYu7klyh42** [MicroCBer/BetterNCM-Installer#5]
Windows11 X86_64 UAC开启 在提示需要管理员权限时点击确定（登录账户有管理员权限）后安装失败（没有提示）
云音乐版本：2.10.3（Build：200198）
Installer版本0.1.1 插件版本 0.1.6
是云音乐太新还是插件没跟上？

**Comment by MicroCBer** [comment]
安装失败是窗口打不开还是？

**Comment by cantorxu** [comment]
我的版本也一样，安装完成后网易云没有变化，是我打开方式不对么
![image](https://user-images.githubusercontent.com/73894757/183002310-2e8b4933-c1df-4cb1-ba92-491d8f8777d4.png)
云音乐版本：2.10.3（Build：200198）
Installer版本0.1.1 插件版本 0.1.6

**Comment by harrychen518** [comment]
same,通过installer安装好后，在关于网易云那边也点了安装简洁侧栏、主题，之后重启了，界面丝毫未动。
没有操作证书相关的步骤，因为找不到指引
版本2.9.4（build:199325)(patch:1:fcf4c7d)
Better NCM 版本0.1.6

**Comment by MicroCBer** [comment]
> same,通过installer安装好后，在关于网易云那边也点了安装简洁侧栏、主题，之后重启了，界面丝毫未动。 没有操作证书相关的步骤，因为找不到指引 版本2.9.4（build:199325)(patch:1:fcf4c7d) Better NCM 版本0.1.6

2.10.2进行过一次浏览器版本更新，从远古版本Chrome35更新到Chrome93，你这个应该是因为版本太老了

**Comment by HYu7klyh42** [comment]
> 安装失败是窗口打不开还是？

没有提示的

**Comment by HYu7klyh42** [comment]
> 安装失败是窗口打不开还是？

云音乐关闭状态下，安装器下载完之后云音乐启动有一个弹窗如图
![image](https://user-images.githubusercontent.com/58126324/183044137-e4630fc5-cdfd-40e8-b615-8ec1e1400f51.png)
点击确定后
![image](https://user-images.githubusercontent.com/58126324/183044633-81d62f0c-38b7-4bf8-835b-86f27795c835.png)

**Comment by nilo-int** [comment]
安装后网易云打不开？
