### ISSUE TITLE
我没有C盘，系统盘盘符是B，不能正常使用

### ISSUE THREAD

**Issue by Anpo4906** [MicroCBer/BetterNCM-Installer#69]
能够成功安装但是打开网易云音乐提示
崩溃原因: create directories: 系统找不到指定的路径"c:\betterncm/plugins"

**Comment by MicroCBer** [comment]
在 Installer 内修改数据目录至其他地方

**Comment by Anpo4906** [comment]
噢！可以用了，之前这样试了一次没有成功
