### ISSUE TITLE
安装主题后 UI部分组件配色错误导致看不清

### ISSUE THREAD

**Issue by Redamancy520** [MicroCBer/BetterNCM-Installer#7]
在安装了任意主题后,UI就变成了这样
![image](https://user-images.githubusercontent.com/66308518/183043676-777c7cc5-0bea-4d85-98ee-1d96489d9b24.png)

![image](https://user-images.githubusercontent.com/66308518/183043768-fa9c2ba2-c211-4185-9c30-23696dc3db03.png)
![image](https://user-images.githubusercontent.com/66308518/183044414-07573625-dc8b-40a2-a809-a9d0b6b4556d.png)

经过测试 只有MicroOrange主题UI可以正常显示

网易云版本:2.10.2
BetterNCM:0.1.6

**Comment by MicroCBer** [comment]
https://github.com/MicroCBer/BetterNCM/issues/3
