### ISSUE TITLE
那个我给了管理员权限，访问数啹目录失败哇

### ISSUE THREAD

**Issue by HFDXGONE** [MicroCBer/BetterNCM-Installer#72]
<img width="710" alt="屏幕截图 2024-08-28 232111" src="https://github.com/user-attachments/assets/a2bd0ff5-cb79-4904-9a72-5dee5c0d975e">
那个我给了管理员权限，访问数啹目录失败哇

**Comment by HFDXGONE** [comment]
网易云2.10的也不行哇

**Comment by HFDXGONE** [comment]
<img width="1058" alt="屏幕截图 2024-08-28 232929" src="https://github.com/user-attachments/assets/3b760c23-3060-48f0-a5b9-2af7f9e6ca2c">

**Comment by HFDXGONE** [comment]
好了好了，通过我的一番弱智操作，搞好了@.@

**Comment by std-microblock** [comment]
不要乱改数据目录。。。

**Comment by histion** [comment]
> 好了好了，通过我的一番弱智操作，搞好了@.@

怎么搞好的，求教
