### ISSUE TITLE
安装插件后无法打开网易云

### ISSUE THREAD

**Issue by Ronin-76** [MicroCBer/BetterNCM-Installer#75]
原来可以用，更新了插件，打开显示报错，
重装插件后，无法打开网易云，一删除就可以打开。
尝试过删除C盘的betterncm文件夹，但依旧打不开。

**Comment by smk0327** [comment]
遇到同样的问题

**Comment by Ronin-76** [comment]
问题解决了，安装了微软常用运行库合集后，再运行就可以了。这里是运行库下载地址：https://pan.baidu.com/s/1Mbh3aDEkKhEmpQr6f9jVSA?pwd=drk6 
提取码：drk6
