### ISSUE TITLE
通过 scoop 安装时无法检测路径

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [MicroCBer/BetterNCM-Installer#8]
能否出个手动路径选择或手动安装教程 ?

**Comment by MicroCBer** [comment]
# 手动安装
## Windows
1. 关闭网易云音乐
2. 将`betterncm.exe`放入网易云安装文件夹
3. 将网易云音乐文件夹内`cloudmusic.exe`更名为`cloudmusicn.exe`
4. 将`betterncm.exe`更名为`cloudmusic.exe`
5. 打开网易云-设置-代理，选择自定义代理
6. 设置为 服务器`localhost` 端口`3296` 如图
